version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    command: /bin/sh -c "chown -R www-data:www-data /var/www/html && apache2-foreground"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: vue-app
    container_name: vue-app
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www
    command: npm run dev

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}

volumes:
  dbdata:
    driver: local
